### ISSUE TITLE
Run single process with --process {process}

### ISSUE THREAD

**Issue by aamalev** [aioworkers/aioworkers#125]
cfg.yaml

```yaml
processes:
   p1:
       groups: [a, b, c, d, g]
```

aioworkers -c cfg.yaml --process p1
